--Incompleta:
--Triggerul acesta va efectua urmatoarele operatii:
--Atunci cand are loc una din operatiile insert, update, sau delete din tabelele rezervarilor
--se verifica daca data decazarii este mai mica decat data curenta. Daca da,
--se sterge din tabelul Rezervarilor si se adauga in tabelul Istoric;
--create or replace trigger trig11_rezervare_locatie
--  after insert or update or delete on rezervare_locuinta
--  for each row
--begin
--  --Daca data de decazare a trecut, atunci stergem din acest tabel si inseram in 
--  --istoric
--  if :NEW.data_decazare < sysdate then
--    insert into istoric_rezervare_locuinta values (:NEW.rezervare_id, 
--      :NEW.locuinta_id, :NEW.client_id, :NEW.numar_persoane, :NEW.data_rezervare, 
--      :NEW.data_cazare, :NEW.data_decazare, :NEW.angajat_id);
--      
--    delete from rezervare_locuinta where rezervare_id = :NEW.rezervare_id;
--  --Daca data de cazare este azi sau a trecut de azi, dar inca nu e decazarea
--  --schimbam statusul 'Rezervat' in 'Cazat' 
--  elsif :NEW.data_cazare < sysdate then
--    update rezervare_locuinta
--    set status = 'Cazat'
--    where rezervare_id = :NEW.rezervare_id;
--  end if;
--end;
--/
--
--create or replace trigger trig11_rezervare_hotel
--  after insert or update or delete on rezervare_hotel
--  for each row
--begin
--  --Daca data de decazare a trecut, atunci stergem din acest tabel si inseram in 
--  --istoric
--  if :NEW.data_decazare < sysdate then
--    insert into istoric_rezervare_hotel values (:NEW.rezervare_id, 
--      :NEW.camera_id, :NEW.client_id, :NEW.numar_persoane, :NEW.data_rezervare, 
--      :NEW.data_cazare, :NEW.data_decazare, :NEW.angajat_id);
--      
--    delete from rezervare_hotel where rezervare_id = :NEW.rezervare_id;
--  --Daca data de cazare este azi sau a trecut de azi, dar inca nu e decazarea
--  --schimbam statusul 'Rezervat' in 'Cazat' 
--  elsif :NEW.data_cazare < sysdate then
--    update rezervare_hotel
--    set status = 'Cazat'
--    where rezervare_id = :NEW.rezervare_id;
--  end if;
--end;
--/