insert into angajat values (1, 'Dalton', 'Maverick', 'dalton.maverick@yahoo.com', 'Director', 34500, 10);
insert into angajat values (2, 'Valencia', 'Aidan', 'valenciaaidan@icloud.com', 'Director', 35400, 20);
insert into angajat values (3, 'Callahan', 'Makayla', 'callahan.makayla@apple.com', 'Director', 91900, 30);
insert into angajat values (4, 'Hensley', 'Molly', 'hensley.molly@gmail.com', 'Director', 16800, 40);
insert into angajat values (5, 'Atkins', 'Tucker', 'atkins_tucker@yahoo.com', 'Director', 54400, 50);
insert into angajat values (6, 'Huffman', 'Emilia', 'huffmanemilia@yahoo.com', 'Consultant', 23200, 20);
insert into angajat values (7, 'Roy', 'Avery', 'roy.avery@outlook.com', 'Consultant', 73100, 30);
insert into angajat values (8, 'Boyer', 'Amir', 'boyeramir@gmail.com', 'Consultant', 44700, 30);
insert into angajat values (9, 'Shields', 'Brian', 'shields.brian@gmail.com', 'Consultant', 73900, 30);
insert into angajat values (10, 'Lin', 'Mya', 'lin.mya@icloud.com', 'Consultant', 36400, 30);
insert into angajat values (11, 'Hancock', 'Kendall', 'hancockkendall@apple.com', 'Consultant', 44200, 30);
insert into angajat values (12, 'Grimes', 'Iker', 'grimesiker@icloud.com', 'Consultant', 28900, 40);
insert into angajat values (13, 'Glenn', 'Melody', 'glenn_melody@outlook.com', 'Agent imobiliar', 84200, 30);
insert into angajat values (14, 'Cline', 'Matteo', 'cline.matteo@outlook.com', 'Agent imobiliar', 78900, 20);
insert into angajat values (15, 'Delacruz', 'Isabel', 'delacruzisabel@yahoo.com', 'Agent imobiliar', 58700, 40);
insert into angajat values (16, 'Camacho', 'Brooke', 'camacho.brooke@apple.com', 'Agent imobiliar', 38500, 20);
insert into angajat values (17, 'Dillon', 'Caden', 'dillon_caden@icloud.com', 'Agent imobiliar', 56000, 30);
insert into angajat values (18, 'Parrish', 'Zayden', 'parrish.zayden@yahoo.com', 'Agent imobiliar', 22300, 40);
insert into angajat values (19, 'Oneill', 'Mckenzie', 'oneill_mckenzie@outlook.com', 'Agent imobiliar', 72800, 20);
insert into angajat values (20, 'Melton', 'Nicole', 'melton.nicole@yahoo.com', 'Agent imobiliar', 62400, 40);
insert into angajat values (21, 'Booth', 'Payton', 'booth_payton@yahoo.com', 'Secretar', 35600, 20);
insert into angajat values (22, 'Kane', 'Margaret', 'kane.margaret@apple.com', 'Secretar', 14500, 20);
insert into angajat values (23, 'Berg', 'Mariah', 'berg_mariah@apple.com', 'Secretar', 35000, 30);
insert into angajat values (24, 'Harrell', 'Andrei', 'harrell.andrei@gmail.com', 'Secretar', 95900, 40);
